Interactions = [
    [ 'HB', 'J', [ 0, 10 ] ],
    [ 'HB', 'J', [ 1, 11 ] ],
    [ 'HB', 'J', [ 2, 12 ] ],
    [ 'HB', 'J', [ 3, 13 ] ],
    [ 'HB', 'J', [ 4, 14 ] ],
    [ 'HB', 'J', [ 0, 5 ] ],
    [ 'HB', 'J', [ 1, 6 ] ],
    [ 'HB', 'J', [ 2, 7 ] ],
    [ 'HB', 'J', [ 3, 8 ] ],
    [ 'HB', 'J', [ 4, 9 ] ],
    [ 'HB', 'J', [ 10, 15 ] ],
    [ 'HB', 'J', [ 11, 16 ] ],
    [ 'HB', 'J', [ 12, 17 ] ],
    [ 'HB', 'J', [ 13, 18 ] ],
    [ 'HB', 'J', [ 14, 19 ] ],
    [ 'HB', 'J', [ 5, 15 ] ],
    [ 'HB', 'J', [ 6, 16 ] ],
    [ 'HB', 'J', [ 7, 17 ] ],
    [ 'HB', 'J', [ 8, 18 ] ],
    [ 'HB', 'J', [ 9, 19 ] ],
    [ 'HB', 'J', [ 0, 9 ] ],
    [ 'HB', 'J', [ 1, 5 ] ],
    [ 'HB', 'J', [ 2, 6 ] ],
    [ 'HB', 'J', [ 3, 7 ] ],
    [ 'HB', 'J', [ 4, 8 ] ],
    [ 'HB', 'J', [ 10, 19 ] ],
    [ 'HB', 'J', [ 11, 15 ] ],
    [ 'HB', 'J', [ 12, 16 ] ],
    [ 'HB', 'J', [ 13, 17 ] ],
    [ 'HB', 'J', [ 14, 18 ] ],
    [ 'HB', 'J', [ 0, 13 ] ],
    [ 'HB', 'J', [ 1, 14 ] ],
    [ 'HB', 'J', [ 2, 10 ] ],
    [ 'HB', 'J', [ 3, 11 ] ],
    [ 'HB', 'J', [ 4, 12 ] ],
    [ 'HB', 'J', [ 5, 18 ] ],
    [ 'HB', 'J', [ 6, 19 ] ],
    [ 'HB', 'J', [ 7, 15 ] ],
    [ 'HB', 'J', [ 8, 16 ] ],
    [ 'HB', 'J', [ 9, 17 ] ],
    [ 'HB', 'Jd', [ 10, 5 ] ],
    [ 'HB', 'Jd', [ 11, 6 ] ],
    [ 'HB', 'Jd', [ 12, 7 ] ],
    [ 'HB', 'Jd', [ 13, 8 ] ],
    [ 'HB', 'Jd', [ 14, 9 ] ],
    [ 'HB', 'Jd', [ 15, 3 ] ],
    [ 'HB', 'Jd', [ 16, 4 ] ],
    [ 'HB', 'Jd', [ 17, 0 ] ],
    [ 'HB', 'Jd', [ 18, 1 ] ],
    [ 'HB', 'Jd', [ 19, 2 ] ]
]