Interactions = [
    [ 'HB', 'J', [ 0, 8 ] ],
    [ 'HB', 'J', [ 1, 9 ] ],
    [ 'HB', 'J', [ 2, 10 ] ],
    [ 'HB', 'J', [ 3, 11 ] ],
    [ 'HB', 'J', [ 0, 4 ] ],
    [ 'HB', 'J', [ 1, 5 ] ],
    [ 'HB', 'J', [ 2, 6 ] ],
    [ 'HB', 'J', [ 3, 7 ] ],
    [ 'HB', 'J', [ 8, 12 ] ],
    [ 'HB', 'J', [ 9, 13 ] ],
    [ 'HB', 'J', [ 10, 14 ] ],
    [ 'HB', 'J', [ 11, 15 ] ],
    [ 'HB', 'J', [ 4, 12 ] ],
    [ 'HB', 'J', [ 5, 13 ] ],
    [ 'HB', 'J', [ 6, 14 ] ],
    [ 'HB', 'J', [ 7, 15 ] ],
    [ 'HB', 'J', [ 0, 5 ] ],
    [ 'HB', 'J', [ 1, 4 ] ],
    [ 'HB', 'J', [ 2, 7 ] ],
    [ 'HB', 'J', [ 3, 6 ] ],
    [ 'HB', 'J', [ 8, 13 ] ],
    [ 'HB', 'J', [ 9, 12 ] ],
    [ 'HB', 'J', [ 10, 15 ] ],
    [ 'HB', 'J', [ 11, 14 ] ],
    [ 'HB', 'J', [ 0, 10 ] ],
    [ 'HB', 'J', [ 1, 11 ] ],
    [ 'HB', 'J', [ 2, 8 ] ],
    [ 'HB', 'J', [ 3, 9 ] ],
    [ 'HB', 'J', [ 4, 14 ] ],
    [ 'HB', 'J', [ 5, 15 ] ],
    [ 'HB', 'J', [ 6, 12 ] ],
    [ 'HB', 'J', [ 7, 13 ] ],
    [ 'HB', 'Jd', [ 8, 4 ] ],
    [ 'HB', 'Jd', [ 9, 5 ] ],
    [ 'HB', 'Jd', [ 10, 6 ] ],
    [ 'HB', 'Jd', [ 11, 7 ] ],
    [ 'HB', 'Jd', [ 12, 3 ] ],
    [ 'HB', 'Jd', [ 13, 2 ] ],
    [ 'HB', 'Jd', [ 14, 1 ] ],
    [ 'HB', 'Jd', [ 15, 0 ] ]
]