site_name: Hydra Documentation
theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
  - pymdownx.superfences 