name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: |
        cp options.mk.sample options.mk
        make
        make test
    - name: run tests
      run: |
        cd test
        ./tests