name: Linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: |
        cmake -S . -B build -D BUILD_TESTING=On
	cmake --build build
    - name: run tests
      run: |
        ./build/test/tests