name: Mac OSX CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: run tests
      run: |
        ./build/test/tests