name: linux CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: |
        cp options.mk.sample options.mk
	sed -i -e 's/lapack = -llapack -lblas/lapack = -framework Accelerate/g' options.mk
        make
        make test
    - name: run tests
      run: |
        cd test
        ./tests